### ISSUE TITLE
build instructions (and dependencies) for js and www should be in the README

### ISSUE THREAD

**Issue by RandomEtc** [simplegeo/polymaps#21]
How to get pygmentize, how to set PYGMENT on the command line, how to edit a particular feature of polymaps.js and have it rebuild, etc.

We should also move most of the caveats/features/bugs etc into the website or this issues list.

**Comment by mbostock** [comment]
Pygments is only required to build the website, not to compile the source. Another option to consider is moving the website to a different branch. Perhaps even moving to the gh-pages branch so that we can use GitHub Pages for hosting and built-in support for Jekyll rather than using Pygments.

I agree that the README.mkd needs an update--it should mostly just be a pointer to the website and the existing issues list. Perhaps it might be a good place to mention planned improvements to the API (such as the transform / init / show changes we discussed).

Ideally, the only build instructions are:
1. Open a shell.
2. Type "make".
3. Hit return.

**Comment by RandomEtc** [comment]
There are some gotchas, aside from PYGMENTS, like if you download a bundle from github then you can't build from source without editing the Makefile because you're not in a git repo. This is the kind of stuff that should be in the README ... whatever you'd need to know if you washed up on a desert island with a macbook and a polymaps zipfile on a flash drive ;)

**Comment by mbostock** [comment]
Is that still true? When I added the compiled JS files to the repo I also removed the inclusion of the HEAD revision. So unless I'm forgetting something there isn't a gut dependency to rebuild anymore.

**Comment by mbostock** [comment]
Fixed. Moved the website to gh-pages, and updated the READMEs to include proper build instructions.

**Comment by RandomEtc** [comment]
Awesome!
