### ISSUE TITLE
If coordinates are encoded as strings, they will not render

### ISSUE THREAD

**Issue by jwdalton** [simplegeo/polymaps#45]
If the coordinates in a GeoJSON file are encoded as strings, they will not render on the map (at least not correctly). It appears that the projection isn't calculated correctly.
Example:
{"geometry":{"type":"Point","coordinates":["-89.404439","43.07333"]},"type":"Feature","properties":{"id":1}}

To fix this, these lines:
 l.lat = coordinates[1];
 l.lon = coordinates[0];
should be changed to this:
 l.lat = parseFloat(coordinates[1]);
 l.lon = parseFloat(coordinates[0]);

**Comment by RandomEtc** [comment]
I'd say there's a bug with the encoding rather than with Polymaps - where does your GeoJSON file come from? 

The GeoJSON spec states that positions are represented by arrays of numbers: http://geojson.org/geojson-spec.html#positions

**Comment by jwdalton** [comment]
I agree that the real bug is in the encoding of the GeoJSON file (which I created and is how I noticed this behavior).
However, supporting this (or detecting that the data is in an invalid format and throwing an error of some sort) would make polymaps more robust and friendly.

**Comment by RandomEtc** [comment]
On reflection that sounds right (got to brush up on my Postel's law), I'll leave this issue open and hopefully we can take care of it in a future release.

**Comment by natevw** [comment]
Trying to keep Garbage In from yielding Garbage Out makes libraries convoluted and buggy. If you want to make a library robust and friendly, add instructive asserts to catch and reject common errors /at the border/, and keep the rest of the code sane.

I'd much rather know that I'm sending incorrect values (strings instead of numbers, unexpected nulls, etc.) than have the library cover it up until I hit an inevitable code path that hasn't been hacked to forgive unexpected garbage.

**Comment by RandomEtc** [comment]
Fair enough. You'll note that nobody has fixed this issue, since it's easier to fix in the data :)

Case closed!
