### ISSUE TITLE
Unhandled exception in IE<9 when loading polymaps.min.js

### ISSUE THREAD

**Issue by jasondavies** [simplegeo/polymaps#46]
It would be nice if `polymaps.js` could be loaded without any exceptions raised, as this prevents scripts further down the page from executing (and potentially trapping any exceptions to display an explanatory message). My workaround for now was to move the polymaps.js script reference to the bottom of the page and inject an onload handler beforehand containing a try/catch.

I'll come up with a patch at some point unless someone beats me to it.

**Comment by RandomEtc** [comment]
What's the exception you're seeing? Not too nasty I hope, Polymaps and IE9 should be just compatible by the time IE9 launches for sure.

There's an IE9 branch that was pretty close to fully working with the beta back in November. Would you be interested in picking this up and bringing it in line with the current version?

Most of the changes I made were to support XDomainRequest instead of XMLHttpRequest for making cross domain requests for data. A couple of other fixes to doctypes and default style elements made everything else work out of the box.

**Comment by RandomEtc** [comment]
Wait, I missed the "<" in the issue title. Got it. Yeah it would be good to detect support, modernizr style, and not run any error-producing code in incompatible browsers.

See also https://github.com/shawnbot/polymaps-svgweb which might help, not sure how far along Shawn has got though.

**Comment by jasondavies** [comment]
See issue #47 for pull request, it was a one-liner in the end!
