### ISSUE TITLE
html doesn't have a doctype declaration so IE9 is switching to quirk mode

### ISSUE THREAD

**Issue by jonfrost** [simplegeo/polymaps#49]
The html does not have a doctype declaration so IE9 is switching to quirk mode. If you could fix those 2 issues then I think PolyMaps will work with IE9.

Should be quick fix.  Thanks

**Comment by RandomEtc** [comment]
Hi Jon,

I think there are a couple of other issues (using `XDomainRequest` where needed for example) but yeah it basically works. See the IE9 branch where I made some of these changes already, although it's a little behind the master branch at the moment since we were waiting for a full release. 

If you'd like to take this on then please feel free to fork and we'll be happy to wrangle any pull requests as soon as we can. If the IE9 branch doesn't merge cleanly let me know and I'll see if I can navigate the needed changes step by step.

**Comment by jonfrost** [comment]
Thanks for taking a look.  I just saw the branch and will review in more detail - thanks.  Protovis looks great too.  

I'm writing an article for MSDN on IE9 and want to cover some of the great work that's being done here.  If I have time to contribute I definitely will.
