### ISSUE TITLE
Does polymaps only support coordinates in lat/long pairs?

### ISSUE THREAD

**Issue by stodge** [simplegeo/polymaps#52]
Does polymaps only support coordinates in lat/long pairs? My dataset isn't lat/longs - it's basic X,Y originating at 0,0. Thanks

**Comment by mbostock** [comment]
In Polymaps (and Modest Maps) terminology, locations are latitude-longitude pairs, and coordinates are x-y-z triples. So, if you have data that's already in Cartesian coordinates and does not need to be projected, you can use the coordinate-point mapping to figure out where to position them on screen.

That said, the GeoJSON layer currently only supports location data, and you can't customize the projection (spherical mercator). So you may need to provide your own layer implementation, instead of using the built-in `po.geoJson`.
