### ISSUE TITLE
svg needs overflow:hidden for IE9

### ISSUE THREAD

**Issue by RandomEtc** [simplegeo/polymaps#9]
Safari and Firefox add it by default, IE doesn't.

**Comment by mbostock** [comment]
This is probably something that will need to be fixed by the client, rather than by Polymaps. Polymaps does not currently take any responsibility for creating SVG elements, so probably shouldn't assume that setting overflow:hidden is the right thing. Instead, do something like:

```
<style type="text/css">
  svg {
    overflow: hidden;
  }
</style>
```

But I'd be curious to see how it's actually broken without this.

**Comment by RandomEtc** [comment]
Fixed in various style sheets in ie9 branch.
